# Generated by Django 3.2.5 on 2026-05-21 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='document',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
