# Generated by Django 3.2.5 on 2026-05-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20260521_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='is_processed',
        ),
        migrations.AlterField(
            model_name='document',
            name='extracted_text',
            field=models.TextField(default='None'),
        ),
    ]
