# Generated by Django 3.2.5 on 2026-05-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20260522_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='extracted_text',
            field=models.TextField(default='None', editable=False),
        ),
    ]
