# Generated by Django 3.2.5 on 2026-05-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_extracted_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
